# Uncomment this line to define a global platform for your project
platform :ios, '7.1'
use_frameworks!

target 'WayThere' do
    pod 'Alamofire', '~> 1.2'
    pod 'SwiftyJSON', '~> 2.2'
    pod 'MagicalRecord'
end

target 'WayThereTests' do
    pod 'Nimble', '~> 0.4.0'
end

